### ISSUE TITLE
Очепятки

### ISSUE THREAD

**Issue by aleksplast** [lexain12/BinaryTranslator#1]
Команд: https://github.com/lexain12/BinaryTranslator/blob/0c00de42c9a515dd3d5928cc2b6134e2f94f7995/README.md?plain=1#LL17C25-L17C25

Промежуточном
https://github.com/lexain12/BinaryTranslator/blob/0c00de42c9a515dd3d5928cc2b6134e2f94f7995/README.md?plain=1#L62

Коэффициент: https://github.com/lexain12/BinaryTranslator/blob/0c00de42c9a515dd3d5928cc2b6134e2f94f7995/README.md?plain=1#L115

**Comment by dodokek** [comment]
Да, Виктор, поправьте.

**Comment by lexain12** [comment]
Да, спасибо большое, что посмотрели мой readme. Все исправил!
